spring:
  profiles:
    active: local
  application:
    name: nabd
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  data:
    redis:
      timeout: 2000ms
  elasticsearch:
    connection-timeout: 10s
  cache:
    type: redis
    redis:
      time-to-live: 600s
      cache-null-values: true

app:
  storage:
    upload-dir: uploads/media
    max-file-size: 500MB

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    bucket: ${AWS_BUCKET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  paths-to-match:
    - /api/**
  show-actuator: true