spring:
  application:
    name: nabd
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:nabd_db}
    username: ${DB_USERNAME:nabd_user}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
  elasticsearch:
    uris: http://${ES_HOSTS:elasticsearch}:${ES_PORT:9200}
    connection-timeout: 10s
  cache:
    type: redis
    redis:
      time-to-live: 600s
      cache-null-values: true

app:
  storage:
    type: local
    upload-dir: uploads/media
    max-file-size: 500MB

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_DEFAULT_REGION}
    bucket: ${S3_BUCKET_NAME}

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false